test_that("batch_downloader works as expected", {
  skip("batch_downloader requires API call")

  api_call_n <- paste0(url, "api/outbreaks/", outbreak_id, "/cases/count")
  api_call_get <- paste0(url, "api/outbreaks/", outbreak_id, "/cases")
  res <- batch_downloader(
    url = url,
    username = username,
    password = password,
    api_call_n = api_call_n,
    api_call_get = api_call_get,
    batch_size = 50000
  )


  expect_s3_class(res, "tbl_df")
  expect_s3_class(res, "data.frame")
  expect_identical(dim(res), c(13L, 153L))
  expect_identical(
    colnames(res),
    c("firstName", "gender", "wasContact", "safeBurial", "classification",
      "investigationStatus", "riskLevel", "transferRefused", "vaccinesReceived",
      "id", "outbreakId", "visualId", "lastName", "dob", "occupation",
      "documents", "addresses", "dateOfReporting",
      "isDateOfReportingApproximate", "dateOfLastContact", "dateOfOnset",
      "dateRanges", "classificationHistory", "hasRelationships",
      "relationshipsRepresentation", "numberOfExposures", "numberOfContacts",
      "usualPlaceOfResidenceLocationId", "responsibleUserId", "createdAt",
      "createdBy", "updatedAt", "updatedBy", "createdOn", "deleted",
      "dateBecomeCase", "wasCase", "active", "followUpHistory",
      "isDateOfOnsetApproximate", "outcomeId", "riskReason", "pregnancyStatus",
      "dateOfOutcome", "dateOfInfection", "middleName",
      "questionnaireAnswers.would_you_like_to_complete_who_basic_case_questionnaire", # nolint
      "questionnaireAnswers.Case_WhichForm",
      "questionnaireAnswers.report_test_reason",
      "questionnaireAnswers.Comcond_present",
      "questionnaireAnswers.patinfo_occuhcw",
      "questionnaireAnswers.expo_travel",
      "questionnaireAnswers.expo_visit_healthcare",
      "questionnaireAnswers.patcourse", "questionnaireAnswers.Comcond_select",
      "questionnaireAnswers.specify_places_and_dates_for_up_to_3_locations_below", # nolint
      "questionnaireAnswers.expo_travel_country1",
      "questionnaireAnswers.expo_travel_city1",
      "questionnaireAnswers.expo_travel_date1",
      "questionnaireAnswers.FA0_UniqueIDClustNumber",
      "questionnaireAnswers.FA0_datacollector_name",
      "questionnaireAnswers.FA0_datacollector_institution",
      "questionnaireAnswers.FA0_datacollector_telephone",
      "questionnaireAnswers.FA0_datacollector_email",
      "questionnaireAnswers.FA0_caseidentifier_email",
      "questionnaireAnswers.FA0_caseidentifier_socialnumber",
      "questionnaireAnswers.FA0_case_countryresidence",
      "questionnaireAnswers.FA0_respondent_ispatient",
      "questionnaireAnswers.FA0_symptoms_caseshowssymptoms",
      "questionnaireAnswers.FA0_respiratorysample_collectedYN",
      "questionnaireAnswers.FA0_clinicalcomplications_ARDS",
      "questionnaireAnswers.FA0_clinicalcomplications_pneumoniachestXray",
      "questionnaireAnswers.FA0_symptom_fever",
      "questionnaireAnswers.FA0_symptom_sorethroat",
      "questionnaireAnswers.FA0_symptom_runnynose",
      "questionnaireAnswers.FA0_symptom_cough",
      "questionnaireAnswers.FA0_symptom_shortnessofbreath",
      "questionnaireAnswers.FA0_symptom_vomiting",
      "questionnaireAnswers.FA0_symptom_nausea",
      "questionnaireAnswers.FA0_symptom_diarrhea",
      "questionnaireAnswers.FA0_symptom_taste", "questionnaireAnswers.test",
      "questionnaireAnswers.which_date_omicron_was_found",
      "questionnaireAnswers.place_of_death",
      "questionnaireAnswers.patinfo_occuhcw_country",
      "questionnaireAnswers.patinfo_occuhcw_city",
      "questionnaireAnswers.patinfo_occuhcw_name",
      "questionnaireAnswers.country_2",
      "questionnaireAnswers.city_2", "questionnaireAnswers.date_2",
      "questionnaireAnswers.FA1_UniqueIDClustNumber",
      "questionnaireAnswers.FA1_FurtherCaseClassification",
      "questionnaireAnswers.FA1_datacollector_name",
      "questionnaireAnswers.FA1_datacollector_institution",
      "questionnaireAnswers.FA1_datacollector_telephone",
      "questionnaireAnswers.FA1_datacollector_email",
      "questionnaireAnswers.FA1_respondent_ispatient",
      "questionnaireAnswers.FA1_caseidentifier_email",
      "questionnaireAnswers.FA1_caseidentifier_socialnumber",
      "questionnaireAnswers.FA1_case_countryresidence",
      "questionnaireAnswers.FA1_case_nationality",
      "questionnaireAnswers.FA1_case_ethnicity",
      "questionnaireAnswers.FA1_case_responsiblehealthcentre",
      "questionnaireAnswers.FA1_case_nurseryschoolcollege",
      "questionnaireAnswers.FA1_carecentre_practicename",
      "questionnaireAnswers.FA1_carecentre_treatingphysicianname",
      "questionnaireAnswers.FA1_carecentre_casepartofoutbreak",
      "questionnaireAnswers.FA1_carecentre_telephone",
      "questionnaireAnswers.FA1_carecentre_fax",
      "questionnaireAnswers.FA1_carecentre_address",
      "questionnaireAnswers.FA1_symptoms_caseshowssymptoms",
      "questionnaireAnswers.FA1_symptoms_healthfacilityvisitedYN",
      "questionnaireAnswers.FA1_complications_mechanicalventilation",
      "questionnaireAnswers.FA1_complications_ARDS",
      "questionnaireAnswers.FA1_complications_acuterenalfailure",
      "questionnaireAnswers.FA1_complications_cardiacfailure",
      "questionnaireAnswers.FA1_complications_consumptivecoagulopathy",
      "questionnaireAnswers.FA1_complications_pneumoniachestXray",
      "questionnaireAnswers.FA1_complications_other",
      "questionnaireAnswers.FA1_complications_EMOrequired",
      "questionnaireAnswers.FA1_complications_hypotensionrequiringvasopressors",
      "questionnaireAnswers.FA1_preexistingconditions_obesity",
      "questionnaireAnswers.FA1_preexistingconditions_cancer",
      "questionnaireAnswers.FA1_preexistingconditions_diabetes",
      "questionnaireAnswers.FA1_preexistingconditions_HIVotherimmunedeficiency",
      "questionnaireAnswers.FA1_preexistingconditions_heartdisease",
      "questionnaireAnswers.FA1_preexistingconditions_asthmarequiringmedication", # nolint
      "questionnaireAnswers.FA1_preexistingconditions_chroniclungdiseasenonasthma", # nolint
      "questionnaireAnswers.FA1_preexistingconditions_chronicliverdisease",
      "questionnaireAnswers.FA1_preexistingconditions_chronichaematologicaldisorder", # nolint
      "questionnaireAnswers.FA1_preexistingconditions_chronickidneydisease",
      "questionnaireAnswers.FA1_preexistingconditions_chronicneurological",
      "questionnaireAnswers.FA1_preexistingconditions_organorbonemarrowrecipient", # nolint
      "questionnaireAnswers.FA1_preexistingconditions_otherpreexistingcondition", # nolint
      "questionnaireAnswers.FA1_healthcareinteractions_contactemergencynumber",
      "questionnaireAnswers.FA1_priorXdayexposure_travelleddomestically",
      "questionnaireAnswers.FA1_priorXdayexposure_travelledinternationally",
      "questionnaireAnswers.FA1_priorXdayexposure_contactwithcase",
      "questionnaireAnswers.FA1_priorXdayexposure_massgathering",
      "questionnaireAnswers.FA1_priorXdayexposure_exposedtosimilarillness",
      "questionnaireAnswers.FA1_priorXdayexposure_locationexposure",
      "questionnaireAnswers.FA1_priorXdayexposure_inpatient",
      "questionnaireAnswers.FA1_priorXdayexposure_outpatient",
      "questionnaireAnswers.FA1_priorXdayexposure_traditionalhealer",
      "questionnaireAnswers.FA1_formcompleted", "age.years", "age.months",
      "duplicateKeys.name", "duplicateKeys.document",
      "followUp.originalStartDate", "followUp.startDate", "followUp.endDate",
      "followUp.status")
  )

  expect_identical(
    unname(sapply(res[1, ], class)),
    c("character", "character", "logical", "logical", "character", "character",
      "character", "logical", "list", "character", "character", "character",
      "character", "character", "character", "list", "list", "character",
      "logical", "character", "character", "list", "list", "logical", "list",
      "integer", "integer", "character", "character", "character", "character",
      "character", "character", "character", "logical", "character", "logical",
      "logical", "list", "logical", "character", "character", "character",
      "character", "character", "character", "list", "list", "list", "list",
      "list", "list", "list", "list", "list", "list", "list", "list", "list",
      "list", "list", "list", "list", "list", "list", "list", "list", "list",
      "list", "list", "list", "list", "list", "list", "list", "list", "list",
      "list", "list", "list", "list", "list", "list", "list", "list", "list",
      "list", "list", "list", "list", "list", "list", "list", "list", "list",
      "list", "list", "list", "list", "list", "list", "list", "list", "list",
      "list", "list", "list", "list", "list", "list", "list", "list", "list",
      "list", "list", "list", "list", "list", "list", "list", "list", "list",
      "list", "list", "list", "list", "list", "list", "list", "list", "list",
      "list", "list", "list", "list", "list", "list", "list", "list", "list",
      "list", "list", "list", "list", "list", "integer", "integer", "list",
      "list", "character", "character", "character", "character")
  )
})
